pipeline:
  name: PLN-CI-003
  identifier: PLNCI003
  projectIdentifier: senthilproj01
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: senthilgitconn03
        repoName: hands-on-workbook
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: buildJar
        identifier: buildJar
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Maven_Build
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.9.0-eclipse-temurin-17
                    shell: Sh
                    command: |-
                      cd /harness/resources/simple-java-app-01
                      mvn clean package
                      find ./target
