pipeline:
  name: PLN-CI-001
  identifier: PLNCI001
  projectIdentifier: senthilproj01
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec:
              size: small
              imageSpec:
                imageName: ubuntu-latest
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "Hello building step"
